### PR TITLE
Remove min value of 0.

### PR DESCRIPTION
**Pull request by dabail10**

### CODE REVIEW

**Comment by bertinia** [comment]
@dabail10 can you add a comment to this PR regarding what test
cases where run with this code change?

**Comment by dabail10** [comment]
I did no testing of this, as it was a return to an older version that worked. Are there some standard tests with the CESM Postprocessing that I could run?

Dave

**Comment by bertinia** [comment]
@dabail10 there aren't any standard tests but if you have some existing
ice average and climo files from a previous postprocessing case, then you 
can test the changes by running the ice_diagnositics and pointing to your
sandbox using the POSTPROCESS_PATH env var.

**Comment by dabail10** [comment]
Ok. I tested the changes with an existing set of climatologies. The plots are here and everything I expected.

http://webext.cgd.ucar.edu/B1850/b.e20.B1850.f09_g17.pi_control.all.190/ice/b.e20.B1850.f09_g17.pi_control.all.190-b.e11.B1850C5CN.f09_g16.005/yrs1-141/

**Pull request merged**
