### PR TITLE
Add support for SIMIP variable names.

### PR DESCRIPTION
**Pull request by dabail10**
This is the first part of the commits to get the post-processing to recognize the SIMIP variable names. The main ones affected are:

Tsfc -> sitemptop
snoice ->sidmasssi
flat_ai ->sifllatstop
fsens_ai ->siflsenstop
fsalt_ai->siflsaltbot
uvel->siu
vvel->siv

The HTML files need to be redone so they accept either name. For now, I need to manually edit the HTML files.

For the vector plots, I removed "uvel" from the png file names so either will be accepted. I have tested this with two of the CMIP6 historical runs. For example, look here:

http://webext.cgd.ucar.edu/BHIST/b.e21.BHIST.f09_g17.CMIP6-historical.003/ice/b.e21.BHIST.f09_g17.CMIP6-historical.003-b.e21.BHIST.f09_g17.CMIP6-historical.001/yrs1850-2005

http://webext.cgd.ucar.edu/BHIST/b.e21.BHIST.f09_g17.CMIP6-historical.002/ice/b.e21.BHIST.f09_g17.CMIP6-historical.002-b.e21.BHIST.f09_g17.CMIP6-historical.001/yrs1850-2005/

Note that ICEDIAG_VAR_NAME_TYPE_CONT and DIFF are changed now to be CSIM/CICE/SIMIP with the default of SIMIP.

Dave

### CODE REVIEW

**Comment by dabail10** [comment]
Exactly what I am working on now. I am creating contour_simip.html and contour_diff_simip.html. I could use your help to point the scripts at  the appropriate file.

**Comment by dabail10** [comment]
Just committed additional fixes for the HTML templates. Here is an example of model versus obs:

http://webext.cgd.ucar.edu/BHIST/b.e21.BHIST.f09_g17.CMIP6-historical.002/ice2/b.e21.BHIST.f09_g17.CMIP6-historical.002-obs/yrs1850-2005/

**Comment by bertinia** [comment]
@dabail10 - is this PR ready to be merged or are you testing cont vs. diff still?

**Comment by bertinia** [comment]
@dabail10 confirmed that this PR is ready to merge. This PR requires a rebuild of the common virtualenvs on NCAR machines.

**Pull request merged**
